### ISSUE TITLE
Standalone aggregator questions

### ISSUE THREAD

**Issue by federicobond** [opentimestamps/opentimestamps-server#13]
* Should standalone aggregators submit to a single calendar server or could the be configured to post to several of them?
 * How should the standalone aggregator respond to a network error or calendar responding with an error? Log the error, rebuild tree with new digests and retry submission?

**Comment by petertodd** [comment]
Lets make aggregators submit to just a single upstream calendar server - I'm inclined to let the clients decide client-side what calendars they submit to rather than have the aggregators do that. Note how this also means that my naming convention is probably a little wrong - should think about this more.

Again, on the principle of "let the client decide", I think the aggregators shouldn't try to handle errors at all and just act as though the client was connecting directly to the calendar. So if the calendar connection fails, the aggregator should also fail in the same way. That should reduce the amount of code we need to write overall too.

**Comment by federicobond** [comment]
That makes sense, I'll try to push an initial version this week.
