### ISSUE TITLE
You service is sh*t for Bitcoin community :-E

### ISSUE THREAD

**Issue by Perlover** [opentimestamps/opentimestamps-server#14]
Hi,

You service is sh*t for Bitcoin community :-E
You use UTXO for proof and a database of UTXO permanently grows from your proof transactions!
You could use OP_RETURN as it do https://proofofexistence.com/

It's right way!

**Comment by RCasatta** [comment]
We don't pollute the UTXO cause we use OP_RETURN as well [example](https://blockchain.info/tx/8465d34ede9e3387cfd7aacae880cfc86a5bdc603d8822e3b0e7c1369f8acfa8).
Moreover, instead of doing just 1 proof for every transaction like the service you mention, we use a merkle tree to perform multiple timestamp at once, as [example](https://petertodd.org/2017/carbon-dating-the-internet-archive-with-opentimestamps) here we stamped 750 million documents with one transaction.
When you post an issue, please avoid cross posting [here](https://github.com/opentimestamps/java-opentimestamps/issues/6) and [here](https://github.com/opentimestamps/javascript-opentimestamps/issues/3) and [here](https://github.com/opentimestamps/opentimestamps.org/issues/17).
