### ISSUE TITLE
High cumulated cpu usage

### ISSUE THREAD

**Issue by RCasatta** [opentimestamps/opentimestamps-server#23]
I recently noticed high cumulated cpu usage from the calendar server.
From the log I saw my server took more than 2 minutes to process a block. (I admit it's a shitty cpu but it's too much anyway)
After investigation I found the bottleneck is the make_timestamp_from_block method which is called for every past unconfirmed tx. Recently network conditions caused my server to have about 300 prior transactions and this caused the long processing.
I wrote a simple test case that confirmed my suspect and created an optimized version of the function in this [commit](https://github.com/RCasatta/opentimestamps-server/commit/05b4ff1fdc30ebb94796577d9f80657c1db48798).
The optimization rely on serializing the entire block out of the cycle and searching the digest inside this data, immediately exiting from the actual function if not found (avoiding serializing every tx every time). This is about 50 times faster in the worst case scenario.
I am currently testing this code in the finney server before making the PR. 
 @petertodd what do you think?

**Comment by petertodd** [comment]
I think an even better way to do it would be to change `make_timestamp_from_block()` to take an array of digests, checking each one, and return the timestamp for the first digest found.

Note that you should pass that function digests sorted most recent commitment first - `make_timestamp_from_block()` will return digests found in transactions that we *didn't* make too, so we want to first try the most recent commitments because they'll commit to the largest sized merkle tree. This could be relevant in cases where someone makes a timestamp tx for us.

**Comment by RCasatta** [comment]
yeah, my solution is focused to minimize the impact and maximize performance but sure the array of digest it's better.
However I was giving for granted `self.unconfirmed_txs` was sorted from the most recent to the oldest to search for the largest merkle tree, but apparently it's not or I am missing something.

**Comment by petertodd** [comment]
Just checked, and right now in both master and my segwit branch, it checks the unconfirmed_txs in the wrong order, oldest first.

So you'll end up fixing that too! :)

**Comment by petertodd** [comment]
And yeah, I figure if we're gonna change this, we might as well just fix it and do the right thing.
