### ISSUE TITLE
[Help] Question about specifying otsd port

### ISSUE THREAD

**Issue by GTP95** [opentimestamps/opentimestamps-server#75]
Hello,
The readme states that for public servers I should put inside ~/.otsd/calendar/uri an URL that can be consistently reached by clients and a port. My question is: since for public servers it's suggested to run otsd behind a proxy (I will use nginx) should I put in the above file the port on which the proxy is listening and specify otsd's port in some other way or should I put otsd's port no matter on which port the proxy will be listening?
Thanks for the clarification and have a nice weekend.

**Comment by RCasatta** [comment]
A client reading a ots receipt coming from your server must find the information to reach your server to upgrade the receipt. 
Since the calendar is behind a proxy, it's the address of the proxy, the port could be omitted if it is port 80.
Please read some other issues in this repository for informations about the reasons to (not) run a server

**Comment by GTP95** [comment]
Thanks for your answer, and I know about the public calendar servers but I've explained why I'll host one myself in another issue. I have one more question: if the port I'm specifying there is the one where the proxy is listening, how should I tell otsd which port is should use?

**Comment by RCasatta** [comment]
`--rpc-port` see https://github.com/opentimestamps/opentimestamps-server/blob/master/otsd#L56

**Comment by GTP95** [comment]
Thanks! Probably I'll make a pull request adding those infos in the readme
