### ISSUE TITLE
Potential issue with implementation: More open to hash collisions when it doesn’t have to be

### ISSUE THREAD

**Issue by Joshfindit** [opentimestamps/opentimestamps-server#89]
I found this project because I’ve been pondering similar questions for a few years, and publicly storing file hashes is viable for specific kinds of files (it’s suboptimal for photos/videos since you really need to store perceptual hashes, but I digress), but there is one major (resolvable) obstacle:

**Given enough time, it is likely that any specific hash method will be “cracked” and allow someone to create a different file that matches the same hash.**

One technique is to record the file-size as well since it’s a trivial change that makes an intentional collision *much* harder. Git does this to avoid accidental collisions at scale.

Another is to store/compare multiple different hashes for the same file. The more algorithms used, the more confident the verification can be.

I’d suggest at minimum adding the file sizes to the hash as it’s a tiny amount of easily-obtained data.

**Comment by cisba** [comment]
Hi Josh, consider that algorithms like sha256 are designed to [minimize](https://stackoverflow.com/questions/4014090/is-it-safe-to-ignore-the-possibility-of-sha-collisions-in-practice) collisions, instead of perceptive hashes that aim to maximize them.

Finally I agree, given enough time every algorithm will be cracked, everybody die, the universe will collapse. So I concentrate my efforts locally.

Regards
Emanuele

**Comment by petertodd** [comment]
SHA256 hash collisions would invalidate the security assumptions that Bitcoin relies on, making the block timestamps themselves unreliable. Thus dealing with SHA256 hash collisions is out of scope for OpenTimestamps.
